import type { StatKey, BackgroundKey } from '../types';
export declare const GENERATION_LENGTH_DAYS = 30;
export declare const GRACE_PERIOD_DANGEROUS = 3;
export declare const GRACE_PERIOD_BOSS = 7;
export declare const DEFAULT_VOTE_WINDOW_HOURS = 24;
export declare const DEMO_VOTE_WINDOW_HOURS = 1;
export declare const TIME_PRESSURE_HOURS_STANDARD = 8;
export declare const TIME_PRESSURE_HOURS_DISADVANTAGED = 6;
export declare const PARTICIPATION_MULTIPLIER_STANDARD = 1.5;
export declare const PARTICIPATION_MULTIPLIER_ADVANTAGED = 1.2;
export declare const PARTICIPATION_ROLLING_DAYS = 7;
export declare const FACTION_FLEE_MULTIPLIER = 0.6;
export declare const FACTION_FIGHT_MULTIPLIER = 0.4;
export declare const FACTION_THRESHOLD_ADVANTAGED_MODIFIER = 0.9;
export declare const CHAIN_PERCENTAGE_THRESHOLD = 0.5;
export declare const CHAIN_DAYS_STANDARD = 2;
export declare const CHAIN_DAYS_ADVANTAGED = 1;
export declare const PREP_ADVANTAGED_RATIO = 1.3;
export declare const PREP_DISADVANTAGED_RATIO = 0.5;
export declare const CHAIN_MIN_RELEVANT_PERCENTAGE = 0.5;
export declare const DEVASTATED_STAT_PENALTY = -2;
export declare const DEVASTATED_NEXT_EVENT_MODIFIER = 0.8;
export declare const BATTLE_CRY_MAX_CHARS = 50;
export declare const DEMO_SEED_DAY = 18;
export declare const DEMO_SEED_CREATURE_NAME = "ZORGATH";
export declare const REDIS_PREFIX = "creature";
export declare const STAGE_THRESHOLDS: Record<number, number>;
export declare const STAT_BACKGROUND_MAP: Record<StatKey, BackgroundKey>;
export type FlairDefinition = {
    id: string;
    label: string;
    streakRequired?: number;
};
export declare const STREAK_FLAIRS: FlairDefinition[];
export declare const CRISIS_FLAIR: FlairDefinition;
export declare const VETERAN_FLAIR: FlairDefinition;
export declare const ORACLE_FLAIR: FlairDefinition;
export declare const MUTATION_CREATOR_FLAIR: FlairDefinition;
export declare const FLAIR_HIERARCHY: readonly string[];
export declare const EVENT_MIN_GAP_DAYS = 4;
export declare const EVENT_SCHEDULE_AHEAD_DAYS = 5;
export declare const ORACLE_WINDOW_DAYS = 3;
