import type { EnvironmentalEventDefinition } from '../types';

export const EVENTS: EnvironmentalEventDefinition[] = [
  {
    id: 'storm',
    name: 'Fırtına',
    tier: 1,
    icon: '🌩️',
    narrative: 'Masif bir fırtına cephesi karaları dövüyor. Kalın zırh tek kalkan.',
    requiredStats: { stats: { armor: 4 }, threshold: 4 },
    crisisType: null,
    crisisWindowHours: 0,
    minDay: 1,
    battleScarSpriteKey: '',
    battleScarName: '',
  },
  {
    id: 'heat_wave',
    name: 'Sıcak Dalga',
    tier: 1,
    icon: '🔥',
    narrative: 'Pişirilmiş topraktan yakıcı sıcaklar yükseliyor. Yalnızca ısıya uyumlu olanlar hayatta kalır.',
    requiredStats: { stats: { heat: 5 }, threshold: 5 },
    crisisType: null,
    crisisWindowHours: 0,
    minDay: 1,
    battleScarSpriteKey: '',
    battleScarName: '',
  },
  {
    id: 'hurricane',
    name: 'Kasırga',
    tier: 1,
    icon: '🌀',
    narrative: 'Dev bir kasırga kıyı boyunca geçiyor. Su ve hız direnci şart.',
    requiredStats: { stats: { aqua: 4, speed: 3 }, threshold: 7 },
    crisisType: null,
    crisisWindowHours: 0,
    minDay: 1,
    battleScarSpriteKey: '',
    battleScarName: '',
  },
  {
    id: 'great_flood',
    name: 'Büyük Sel',
    tier: 2,
    icon: '🌊',
    narrative: 'Yükselen sular yaşam alanını yutmakla tehdit ediyor. Günler süren direnç gerekli.',
    requiredStats: { stats: { aqua: 7 }, threshold: 7 },
    crisisType: 'chain',
    crisisWindowHours: 48,
    minDay: 3,
    battleScarSpriteKey: 'scar_great_flood',
    battleScarName: 'Su Erozyonu',
  },
  {
    id: 'predator_invasion',
    name: 'Predatör İstilası',
    tier: 2,
    icon: '🐾',
    narrative: 'Doruk avcılardan oluşan bir sürü bölgeye girdi. Topluluk seçmeli: kaç ya da savaş.',
    requiredStats: { stats: { speed: 5, armor: 4 }, threshold: 9 },
    crisisType: 'faction',
    crisisWindowHours: 24,
    minDay: 3,
    battleScarSpriteKey: 'scar_predator_invasion',
    battleScarName: 'Avcı Çizikleri',
  },
  {
    id: 'famine',
    name: 'Kıtlık',
    tier: 2,
    icon: '💀',
    narrative: 'Kaynaklar çöktü. Yalnızca kurnaz zihinler gizli kaynakları bulabilir.',
    requiredStats: { stats: { mind: 6 }, threshold: 6 },
    crisisType: 'participation',
    crisisWindowHours: 24,
    minDay: 3,
    battleScarSpriteKey: 'scar_famine',
    battleScarName: 'Açlık Kemikleri',
  },
  {
    id: 'volcano',
    name: 'Volkan Patlaması',
    tier: 2,
    icon: '🌋',
    narrative: 'Volkan uyanıyor ve gökyüzü kızarıyor. Sürekli ısı direnci tek kurtuluş.',
    requiredStats: { stats: { heat: 8 }, threshold: 8 },
    crisisType: 'chain',
    crisisWindowHours: 48,
    minDay: 3,
    battleScarSpriteKey: 'scar_volcano',
    battleScarName: 'Lav Yanık İzi',
  },
  {
    id: 'great_meteor',
    name: 'Büyük Meteor',
    tier: 3,
    icon: '☄️',
    narrative: 'Yıkıcı bir meteor çarpması tehdit ediyor. Anlık karar verilmeli: kaç ya da savaş.',
    requiredStats: { stats: { speed: 7, armor: 7 }, threshold: 14 },
    crisisType: 'time_pressure',
    crisisWindowHours: 8,
    minDay: 7,
    battleScarSpriteKey: 'scar_great_meteor',
    battleScarName: 'Meteor Çukuru',
  },
  {
    id: 'ice_age',
    name: 'Buzul Çağı',
    tier: 3,
    icon: '❄️',
    narrative: 'Buzullar ilerliyor ve sıcaklıklar sert düşüyor. Uzun süreli soğuk direnci insanlığın tek umudu.',
    requiredStats: { stats: { cold: 10 }, threshold: 10 },
    crisisType: 'participation',
    crisisWindowHours: 24,
    minDay: 7,
    battleScarSpriteKey: 'scar_ice_age',
    battleScarName: 'Permafrost Kırıkları',
  },
  {
    id: 'cosmic_disease',
    name: 'Kozmik Hastalık',
    tier: 3,
    icon: '🦠',
    narrative: 'Boşluktan gelen gizemli bir patojen yayılıyor. Topluluk bölünmüş: izolasyon mu, direniş mi?',
    requiredStats: { stats: { mind: 7, armor: 6 }, threshold: 13 },
    crisisType: 'faction',
    crisisWindowHours: 24,
    minDay: 7,
    battleScarSpriteKey: 'scar_cosmic_disease',
    battleScarName: 'Bağışıklık Lekeleri',
  },
];

export const EVENT_MAP: Record<string, EnvironmentalEventDefinition> = Object.fromEntries(
  EVENTS.map((e) => [e.id, e])
);
